#+options: toc:nil timestamp:nil
#+title: Super Poli Ball
#+author: Rafael Barone, Renato Rotenberg
#+language: pt-br

#+LaTeX_HEADER: \usepackage[brazil,brazilian]{babel}

* Introdução

Esse é o projeto dos alunos Rafael Barone e Renato Rotenberg da matéria =PCS
3539 - TECNOLOGIA DE COMPUTAÇÃO GRÁFICA=. Esse projeto é um jogo inspirado na
série =Super Monkey Ball=, desenvolvido com o motor de jogos software livre
=Godot=. O desenvolvimento desse projeto irá explorar assuntos estudados em sala
tipicamente abordados em jogos eletrônicos, como transformações geométricas,
modelagem 3D, texturas e iluminação. Em especial, esse projeto fará uso do
suporte embutido do =Godot= à modelagem CSG para a rápida prototipação de
estágios. O projeto está hospedado no [[https://github.com/Brawmario/super-poli-ball][GitHub]].

Play it on [[https://brawmario.itch.io/super-poli-ball][itch.io]]

* Lista de afazeres

** TODO Esboço inicial do projeto

Brainstorming inicial do jogo: mecânicas, interface, organização do projeto.

** TODO Design inicial de estágios

Esboço dos estágios em papel, incluindo geometria, obstáculos e visuais.

** TODO Implementação inicial das mecânicas

Desenvolvimento do "ator" controlado pelo jogador, testes em um estágio simples.

** TODO Desenvolvimento dos estágios

Inicialmente sem se preocupar com os gráficos, apenas com a jogabilidade.
Modelagem com CSG embutido promete acelerar esse processo.

** TODO Desenvolvimento da interface/menus

Criação dos menus do jogo e a implementação da transição entre os diferentes
partes do programa (tela principal, seleção de estágios, transição entre os estágios

** TODO Aperfeiçoamentos gráficos

Texturização dos estágios, aplicação da iluminação, implementação de diferentes
tipos de bola (pedra, madeira, etc.), exploração de shaders para efeitos especiais.

* Licença

#+BEGIN_QUOTE
Este programa é um software livre; você pode redistribuí-lo e/ou
modificá-lo sob os termos da Licença Pública Geral GNU como publicada
pela Free Software Foundation; na versão 3 da Licença, ou
(a seu critério) qualquer versão posterior.

Este programa é distribuído na esperança de que possa ser útil,
mas SEM NENHUMA GARANTIA; sem uma garantia implícita de ADEQUAÇÃO
a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
Licença Pública Geral GNU para mais detalhes.

Você deve ter recebido uma cópia da Licença Pública Geral GNU junto
com este programa. Se não, veja <http://www.gnu.org/licenses/>.
#+END_QUOTE
